name: Deploy EC2 App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Conectarse por SSH y actualizar app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/app
          git pull origin main
          pip3 install -r requirements.txt
          pkill -f flask || true
          nohup flask run --host=0.0.0.0 --port=80 &
